### PR TITLE
Additional parameter (`attrs`) for create() and update() methods.

### PR DESCRIPTION
**Pull request by zlw**
There would be nice if we could pass some additional dictionary to these (`create()` and `update()`).
Now if we won't to add some value we need to override whole method.

With this little change we can do this: [[gist.github.com/863191]]

### CODE REVIEW

**Comment by davedash** [comment]
1. Is this something that should go upstream.
2. Is there a reason these aren't in the request.data object to begin with?
3. Can you subclass BaseHandler

My goal is to not diverge too much from https://bitbucket.org/jespern/django-piston/src as much as possible.

**Comment by zlw** [comment]
I think it would be nice to have this in upstream.

This parameter isn't obligatory, if You won't pass it, everything will work normally, but if You want to add some simple value (as in the example: `User` object, wchich can't be just an ID passed in POST/PUT data), You can do this.

I've pulled a request to https://bitbucket.org/jespern/django-piston/ but I think this repo is dead. Last change was 6 month ago so I don't think that jespern will merge it.

**Comment by davedash** [comment]
Why would you be passing a `User` object?

If you're dealing with a logged in user trying to make these calls, that should be handled in authentication, and then user request.user.  Zamboni has an example of that.

**Comment by zlw** [comment]
By `User` object i meant `request.user`

User was just an example. In my app I needed to pass some object's ID (`curl ... -d "tasklist=1"`) in data and than pass that object (`TaskList.objects.get(pk=tasklist)`) when i've been saving model. 

With my changes in `BaseHandler.create()` I can do this much much simpler (like in the example from my first post). Without it I'll need to override create() in this handler and than in another, and another etc. With this tiny change, out handlers are more DRY, I think.

btw. `request.user` **is** representation of `User` or `AnonymousUser` (if user isn't currently logged-in) ;)

**Comment by davedash** [comment]
I don't think this is the right approach.  Why don't you just do Tasklist.objects.get in your methods rather than passing the handler.

Also I don't think you'd need to override create() more than once.  If you really think you need these extra data, then subclass it once, and then use that subclassed BaseHandler everywhere.

Sounds like you've got some working code that reuqires this, show it to me because I'm sure there's a way around this.  Dealing with stuff that isn't request.data seems wrong.

**Comment by andymckay** [comment]
These patches should go upstream on the bitbucket repo, not into the mozilla repo. This was forked here so we could use our existing git tools to pull it into our builds.

**Pull request closed without merging**
